apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: hcloud-csi
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - SYS_ADMIN
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'hostPath'
    - 'secret'
    - 'emptyDir'
  hostNetwork: true
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
  allowedHostPaths:
  - pathPrefix: "/var/lib/kubelet"
  - pathPrefix: "/dev"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hcloud-csi-psp
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - hcloud-csi
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hcloud-csi-psp
subjects:
  - kind: ServiceAccount
    name: hcloud-csi
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: hcloud-csi-psp
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: hcloud-csi-node
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - SYS_ADMIN
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'hostPath'
    - 'secret'
    - 'emptyDir'
  hostNetwork: true
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
  allowedHostPaths:
  - pathPrefix: "/var/lib/kubelet"
  - pathPrefix: "/dev"
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: hcloud-csi-node
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hcloud-csi-node
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - hcloud-csi-node
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hcloud-csi-node
subjects:
  - kind: ServiceAccount
    name: hcloud-csi-node
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: hcloud-csi-node
  apiGroup: rbac.authorization.k8s.io
