apiVersion: v1
kind: ServiceAccount
metadata:
    name: hcloud-csi-node
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hcloud-csi-node
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hcloud-csi-node
subjects:
  - kind: ServiceAccount
    name: hcloud-csi-node
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: hcloud-csi-node
  apiGroup: rbac.authorization.k8s.io
